/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CustomResponse } from '../../models/custom-response';
import { Pageable } from '../../models/pageable';

export interface List6$Params {

/**
 * Filtre par statut du dossier. Omis = tous les statuts.
 */
  status?: 'INCOMPLETE' | 'PENDING_REVIEW' | 'QUALIFIED' | 'REJECTED' | 'BLACKLISTED';
  pageable: Pageable;
}

export function list6(http: HttpClient, rootUrl: string, params: List6$Params, context?: HttpContext): Observable<StrictHttpResponse<CustomResponse>> {
  const rb = new RequestBuilder(rootUrl, list6.PATH, 'get');
  if (params) {
    rb.query('status', params.status, {});
    rb.query('pageable', params.pageable, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CustomResponse>;
    })
  );
}

list6.PATH = '/v1/tenants';
