/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CustomResponse } from '../../models/custom-response';

export interface GetSubRoles1$Params {
  userId: string;
}

export function getSubRoles1(http: HttpClient, rootUrl: string, params: GetSubRoles1$Params, context?: HttpContext): Observable<StrictHttpResponse<CustomResponse>> {
  const rb = new RequestBuilder(rootUrl, getSubRoles1.PATH, 'get');
  if (params) {
    rb.path('userId', params.userId, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CustomResponse>;
    })
  );
}

getSubRoles1.PATH = '/v1/agency/team/{userId}/sub-roles';
