/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CustomResponse } from '../../models/custom-response';

export interface RevokeSubRole1$Params {
  userId: string;
  role: string;
}

export function revokeSubRole1(http: HttpClient, rootUrl: string, params: RevokeSubRole1$Params, context?: HttpContext): Observable<StrictHttpResponse<CustomResponse>> {
  const rb = new RequestBuilder(rootUrl, revokeSubRole1.PATH, 'delete');
  if (params) {
    rb.path('userId', params.userId, {});
    rb.path('role', params.role, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CustomResponse>;
    })
  );
}

revokeSubRole1.PATH = '/v1/agency/team/{userId}/sub-roles/{role}';
