/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PresignedReadUrlResponse } from '../../models/presigned-read-url-response';

export interface GenerateReadUrl$Params {

/**
 * URL complète du fichier (telle que retournée lors de l'upload)
 */
  fileUrl: string;
}

export function generateReadUrl(http: HttpClient, rootUrl: string, params: GenerateReadUrl$Params, context?: HttpContext): Observable<StrictHttpResponse<PresignedReadUrlResponse>> {
  const rb = new RequestBuilder(rootUrl, generateReadUrl.PATH, 'get');
  if (params) {
    rb.query('fileUrl', params.fileUrl, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PresignedReadUrlResponse>;
    })
  );
}

generateReadUrl.PATH = '/v1/storage/presign/read';
