/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PresignedUrlResponse } from '../../models/presigned-url-response';

export interface GeneratePresignedUrl$Params {

/**
 * Bucket cible
 */
  bucket: string;

/**
 * Nom de l'objet (ex: propertyId/uuid.webp). UUID auto si absent.
 */
  key?: string;

/**
 * Durée de validité en secondes (max 3600)
 */
  expires?: number;
}

export function generatePresignedUrl(http: HttpClient, rootUrl: string, params: GeneratePresignedUrl$Params, context?: HttpContext): Observable<StrictHttpResponse<PresignedUrlResponse>> {
  const rb = new RequestBuilder(rootUrl, generatePresignedUrl.PATH, 'get');
  if (params) {
    rb.query('bucket', params.bucket, {});
    rb.query('key', params.key, {});
    rb.query('expires', params.expires, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PresignedUrlResponse>;
    })
  );
}

generatePresignedUrl.PATH = '/v1/storage/presign';
