/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PresignedUrlResponse } from '../../models/presigned-url-response';

export interface PresignPropertyDocument$Params {

/**
 * UUID du bien
 */
  propertyId: string;

/**
 * Type MIME du fichier
 */
  contentType: string;
  expires?: number;
}

export function presignPropertyDocument(http: HttpClient, rootUrl: string, params: PresignPropertyDocument$Params, context?: HttpContext): Observable<StrictHttpResponse<PresignedUrlResponse>> {
  const rb = new RequestBuilder(rootUrl, presignPropertyDocument.PATH, 'get');
  if (params) {
    rb.query('propertyId', params.propertyId, {});
    rb.query('contentType', params.contentType, {});
    rb.query('expires', params.expires, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PresignedUrlResponse>;
    })
  );
}

presignPropertyDocument.PATH = '/v1/storage/presign/property-document';
