/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { StorageUploadResponse } from '../../models/storage-upload-response';

export interface Upload$Params {

/**
 * Bucket cible
 */
  bucket: string;

/**
 * Sous-dossier optionnel dans le bucket
 */
  folder?: string;
      body: {
}
}

export function upload(http: HttpClient, rootUrl: string, params: Upload$Params, context?: HttpContext): Observable<StrictHttpResponse<StorageUploadResponse>> {
  const rb = new RequestBuilder(rootUrl, upload.PATH, 'post');
  if (params) {
    rb.query('bucket', params.bucket, {});
    rb.query('folder', params.folder, {});
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<StorageUploadResponse>;
    })
  );
}

upload.PATH = '/v1/storage/upload';
