/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AdminHotelResponse } from '../../models/admin-hotel-response';

export interface ActivateHotel$Params {
  id: string;
}

export function activateHotel(http: HttpClient, rootUrl: string, params: ActivateHotel$Params, context?: HttpContext): Observable<StrictHttpResponse<AdminHotelResponse>> {
  const rb = new RequestBuilder(rootUrl, activateHotel.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AdminHotelResponse>;
    })
  );
}

activateHotel.PATH = '/v1/admin/partners/hotels/{id}/activate';
