/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AdminUserResponse } from '../../models/admin-user-response';
import { AssignAdminRoleRequest } from '../../models/assign-admin-role-request';

export interface AssignAdminRole$Params {
  userId: string;
      body: AssignAdminRoleRequest
}

export function assignAdminRole(http: HttpClient, rootUrl: string, params: AssignAdminRole$Params, context?: HttpContext): Observable<StrictHttpResponse<AdminUserResponse>> {
  const rb = new RequestBuilder(rootUrl, assignAdminRole.PATH, 'put');
  if (params) {
    rb.path('userId', params.userId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AdminUserResponse>;
    })
  );
}

assignAdminRole.PATH = '/v1/admin/users/{userId}/role';
