/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CustomResponse } from '../../models/custom-response';
import { Pageable } from '../../models/pageable';

export interface ListClients1$Params {
  agencyId?: string;
  hotelId?: string;
  pageable: Pageable;
}

export function listClients1(http: HttpClient, rootUrl: string, params: ListClients1$Params, context?: HttpContext): Observable<StrictHttpResponse<CustomResponse>> {
  const rb = new RequestBuilder(rootUrl, listClients1.PATH, 'get');
  if (params) {
    rb.query('agencyId', params.agencyId, {});
    rb.query('hotelId', params.hotelId, {});
    rb.query('pageable', params.pageable, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CustomResponse>;
    })
  );
}

listClients1.PATH = '/v1/admin/clients';
