/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ClientUserResponse } from '../../models/client-user-response';
import { Pageable } from '../../models/pageable';

export interface ListClients$Params {
  pageable: Pageable;
}

export function listClients(http: HttpClient, rootUrl: string, params: ListClients$Params, context?: HttpContext): Observable<StrictHttpResponse<ClientUserResponse>> {
  const rb = new RequestBuilder(rootUrl, listClients.PATH, 'get');
  if (params) {
    rb.query('pageable', params.pageable, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ClientUserResponse>;
    })
  );
}

listClients.PATH = '/v1/admin/partners/clients';
