/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AdminUserResponse } from '../../models/admin-user-response';

export interface ListAdmins$Params {
}

export function listAdmins(http: HttpClient, rootUrl: string, params?: ListAdmins$Params, context?: HttpContext): Observable<StrictHttpResponse<AdminUserResponse>> {
  const rb = new RequestBuilder(rootUrl, listAdmins.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AdminUserResponse>;
    })
  );
}

listAdmins.PATH = '/v1/admin/users';
