/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AdminAgencyResponse } from '../../models/admin-agency-response';
import { UpdateSubscriptionRequest } from '../../models/update-subscription-request';

export interface UpdateAgencySubscription$Params {
  id: string;
      body: UpdateSubscriptionRequest
}

export function updateAgencySubscription(http: HttpClient, rootUrl: string, params: UpdateAgencySubscription$Params, context?: HttpContext): Observable<StrictHttpResponse<AdminAgencyResponse>> {
  const rb = new RequestBuilder(rootUrl, updateAgencySubscription.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AdminAgencyResponse>;
    })
  );
}

updateAgencySubscription.PATH = '/v1/admin/partners/agencies/{id}/subscription';
