/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AdminDashboardResponse } from '../../models/admin-dashboard-response';

export interface GetAdminDashboard$Params {
}

export function getAdminDashboard(http: HttpClient, rootUrl: string, params?: GetAdminDashboard$Params, context?: HttpContext): Observable<StrictHttpResponse<AdminDashboardResponse>> {
  const rb = new RequestBuilder(rootUrl, getAdminDashboard.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AdminDashboardResponse>;
    })
  );
}

getAdminDashboard.PATH = '/v1/dashboard/admin';
