/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AgencyDashboardResponse } from '../../models/agency-dashboard-response';

export interface GetAgencyDashboard$Params {
  from?: string;
  to?: string;
}

export function getAgencyDashboard(http: HttpClient, rootUrl: string, params?: GetAgencyDashboard$Params, context?: HttpContext): Observable<StrictHttpResponse<AgencyDashboardResponse>> {
  const rb = new RequestBuilder(rootUrl, getAgencyDashboard.PATH, 'get');
  if (params) {
    rb.query('from', params.from, {});
    rb.query('to', params.to, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AgencyDashboardResponse>;
    })
  );
}

getAgencyDashboard.PATH = '/v1/dashboard/agency';
