/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CustomResponse } from '../../models/custom-response';

export interface List$Params {

/**
 * Filtre par statut
 */
  status?: 'OPEN' | 'IN_ANALYSIS' | 'TECHNICIAN_SENT' | 'RESOLVED' | 'CLOSED' | 'CANCELLED';

/**
 * Filtre par agent assigné (UUID)
 */
  assignedToId?: string;
  page?: number;
  size?: number;
}

export function list(http: HttpClient, rootUrl: string, params?: List$Params, context?: HttpContext): Observable<StrictHttpResponse<CustomResponse>> {
  const rb = new RequestBuilder(rootUrl, list.PATH, 'get');
  if (params) {
    rb.query('status', params.status, {});
    rb.query('assignedToId', params.assignedToId, {});
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CustomResponse>;
    })
  );
}

list.PATH = '/v1/tickets';
