/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CustomResponse } from '../../models/custom-response';
import { ScheduleInterventionRequest } from '../../models/schedule-intervention-request';

export interface ScheduleIntervention$Params {
  ticketId: string;
      body: ScheduleInterventionRequest
}

export function scheduleIntervention(http: HttpClient, rootUrl: string, params: ScheduleIntervention$Params, context?: HttpContext): Observable<StrictHttpResponse<CustomResponse>> {
  const rb = new RequestBuilder(rootUrl, scheduleIntervention.PATH, 'patch');
  if (params) {
    rb.path('ticketId', params.ticketId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CustomResponse>;
    })
  );
}

scheduleIntervention.PATH = '/v1/tickets/{ticketId}/schedule';
