/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AddTicketMessageRequest } from '../../models/add-ticket-message-request';
import { CustomResponse } from '../../models/custom-response';

export interface AddMessage$Params {
  ticketId: string;
      body: AddTicketMessageRequest
}

export function addMessage(http: HttpClient, rootUrl: string, params: AddMessage$Params, context?: HttpContext): Observable<StrictHttpResponse<CustomResponse>> {
  const rb = new RequestBuilder(rootUrl, addMessage.PATH, 'post');
  if (params) {
    rb.path('ticketId', params.ticketId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CustomResponse>;
    })
  );
}

addMessage.PATH = '/v1/tickets/{ticketId}/messages';
