/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AddTicketMessageRequest {

  /**
   * Contenu du message
   */
  message?: string;

  /**
   * Visibilité du message : PUBLIC (visible par toutes les parties) ou INTERNAL (note interne équipe SAV uniquement). Défaut : PUBLIC
   */
  messageType?: 'PUBLIC' | 'INTERNAL';
}
