/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AdminDashboardResponse {
  confirmedReservations?: number;
  openTickets?: number;
  pendingReservations?: number;
  propertiesPendingReview?: number;
  publishedProperties?: number;
  totalActiveAgencies?: number;
  totalActiveHotels?: number;
  totalClients?: number;
  totalOwners?: number;
}
