/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AdminHotelResponse {
  active?: boolean;
  city?: string;
  createdAt?: string;
  email?: string;
  id?: string;
  logoUrl?: string;
  name?: string;
  phone?: string;
  stars?: number;
  subscriptionActive?: boolean;
  subscriptionExpiresAt?: string;
  subscriptionPlan?: string;
  totalRooms?: number;
  verified?: boolean;
  verifiedAt?: string;
}
