/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Agence immobilière disponible sur la plateforme UBAX
 */
export interface AgencyResponse {

  /**
   * Adresse du siège social
   */
  address?: string;

  /**
   * Ville d'implantation principale
   */
  city?: string;

  /**
   * Code pays ISO 3166-1 alpha-2
   */
  country?: string;

  /**
   * Description des services de l'agence
   */
  description?: string;

  /**
   * Email professionnel
   */
  email?: string;

  /**
   * Identifiant unique de l'agence
   */
  id?: string;

  /**
   * URL du logo de l'agence
   */
  logoUrl?: string;

  /**
   * Nom commercial de l'agence
   */
  name?: string;

  /**
   * Numéro de téléphone professionnel
   */
  phone?: string;

  /**
   * Agence certifiée par UBAX
   */
  verified?: boolean;

  /**
   * Site web officiel
   */
  website?: string;
}
