/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ExpenseBreakdownItem } from '../models/expense-breakdown-item';
import { RevenueBreakdownItem } from '../models/revenue-breakdown-item';
export interface AgencyDashboardResponse {
  activeContracts?: number;
  expensesByCategory?: Array<ExpenseBreakdownItem>;
  latePaymentsCount?: number;
  netRevenue?: number;
  overdueAmount?: number;
  paidPaymentsCount?: number;
  pendingPaymentsCount?: number;
  periodFrom?: string;
  periodTo?: string;
  publishedProperties?: number;
  recoveryRate?: number;
  reservedProperties?: number;
  revenueByType?: Array<RevenueBreakdownItem>;
  totalExpenses?: number;
  totalProperties?: number;
  totalRevenue?: number;
}
