/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ApplicationStatusLogResponse {
  changedAt?: string;
  changedByName?: string;
  comment?: string;
  id?: string;
  newStatus?: 'PENDING' | 'UNDER_REVIEW' | 'INCOMPLETE' | 'APPROVED' | 'REJECTED';
  previousStatus?: 'PENDING' | 'UNDER_REVIEW' | 'INCOMPLETE' | 'APPROVED' | 'REJECTED';
}
