/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AssignSubRolesRequest {

  /**
   * Liste des sous-rôles à assigner selon le scope :
   * - UBAX_INTERNAL : DIRECTEUR_GENERAL, SUPPORT_CLIENT, OPERATIONS, FINANCE, COMMERCIAL
   * - AGENCE : DIRECTEUR_AGENCE, COMMERCIAL, COMPTABLE_AGENCE, AGENT_SAV
   * - HOTEL : GERANT_HOTEL, RECEPTIONNISTE, COMPTABLE_HOTEL, RESPONSABLE_HEBERGEMENT
   */
  roles?: Array<string>;

  /**
   * Portée des sous-rôles
   */
  scope: 'UBAX_INTERNAL' | 'AGENCE' | 'HOTEL';
}
