/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Créneau disponible avec nombre de places
 */
export interface AvailableSlot {

  /**
   * Vrai si 1 seule place reste (info pour UI: marquer comme "peu de places")
   */
  almostFull?: boolean;

  /**
   * Nombre de places disponibles
   */
  available?: number;

  /**
   * Créneau horaire
   */
  slot?: string;
}
