/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BailleurAgencyResponse {
  agencyEmail?: string;
  agencyId?: string;
  agencyLogo?: string;
  agencyName?: string;
  agencyPhone?: string;
  linkedAt?: string;
}
