/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Requête d'annulation d'une réservation
 */
export interface CancelReservationRequest {

  /**
   * Motif d'annulation
   */
  reason: string;
}
