/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ClientUserResponse {
  active?: boolean;
  avatarUrl?: string;
  city?: string;
  createdAt?: string;
  email?: string;
  emailVerified?: boolean;
  firstName?: string;
  id?: string;
  identityVerified?: boolean;
  lastLoginAt?: string;
  lastName?: string;
  phone?: string;
  phoneVerified?: boolean;
}
