/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Configuration des créneaux de visite disponibles
 */
export interface ConfigureVisitAvailabilityDto {

  /**
   * Dates fermées (vacances, congés) au format YYYY-MM-DD
   */
  blackoutDates?: Array<string>;

  /**
   * Nombre maximum de visites par créneau
   */
  maxVisitsPerSlot?: number;

  /**
   * ID du bien à configurer
   */
  propertyId: string;

  /**
   * Créneaux par jour de semaine (0=Dimanche, 1=Lundi, ..., 6=Samedi). null ou absent = jour fermé
   */
  timeSlots: {
[key: string]: Array<string>;
};
}
