/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Confirmation d'une demande de visite par l'agence
 */
export interface ConfirmVisitRequestDto {

  /**
   * Notes de l'agence (optionnel)
   */
  agencyNotes?: string;

  /**
   * Date de confirmation
   */
  confirmedDate: string;

  /**
   * Créneau confirmé
   */
  confirmedTimeSlot?: string;
}
