/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TicketAttachmentInput } from '../models/ticket-attachment-input';
export interface CreateTicketRequest {

  /**
   * Images ou vidéos de l'incident (URLs pré-uploadées via GET /v1/storage/presign/ticket-attachment). Optionnel — max recommandé : 5 fichiers.
   */
  attachments?: Array<TicketAttachmentInput>;

  /**
   * Catégorie métier de l'incident (alignée avec TECHNICIEN_PROFESSION)
   */
  category?: 'PLOMBIER' | 'ELECTRICIEN' | 'SERRURIER' | 'MENUISIER' | 'MACON' | 'PEINTRE' | 'CLIMATISATION' | 'VITRERIE' | 'JARDINAGE' | 'NETTOYAGE' | 'DESINSECTISATION' | 'AUTRE';

  /**
   * Identifiant du contrat dans le cadre duquel l'incident est signalé
   */
  contractId: string;

  /**
   * Description détaillée de l'incident (20 caractères minimum)
   */
  description?: string;

  /**
   * Niveau d'urgence (défaut : NORMAL)
   */
  priority?: 'LOW' | 'NORMAL' | 'HIGH' | 'URGENT';

  /**
   * Titre court de l'incident
   */
  title?: string;
}
