/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateTicketRequest {

  /**
   * Catégorie de l'incident
   */
  category?: 'LEAK' | 'ELECTRICAL' | 'LOCK' | 'PLUMBING' | 'APPLIANCE' | 'STRUCTURE' | 'PEST' | 'COMMON_AREA' | 'OTHER';

  /**
   * Identifiant du contrat dans le cadre duquel l'incident est signalé
   */
  contractId: string;

  /**
   * Description détaillée de l'incident
   */
  description?: string;

  /**
   * Niveau d'urgence (défaut : NORMAL)
   */
  priority?: 'LOW' | 'NORMAL' | 'HIGH' | 'URGENT';

  /**
   * Titre court de l'incident
   */
  title?: string;
}
