/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateTechnicienRequest {
  address?: string;

  /**
   * URL de l'avatar (déjà uploadé via /v1/storage)
   */
  avatarUrl?: string;
  email?: string;
  firstName?: string;
  lastName?: string;
  phone?: string;

  /**
   * Valeur de la code-list TICKET_CATEGORY
   */
  profession?: string;
}
