/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateContractRequest {

  /**
   * Taux de commission agence (%)
   */
  agencyCommissionRate?: number;

  /**
   * Type de contrat :
   * - `LEASE` — Bail de location (monthlyRent requis)
   * - `SALE` — Acte de vente (salePrice requis)
   * - `RENT_TO_OWN` — Location-vente : le locataire verse une mensualité (monthlyInstallment) qui s'impute sur le prix total du bien (salePrice) jusqu'au terme fixé par endDate
   * - `RESERVATION` — Contrat de réservation (reservationDeposit requis)
   * - `MANDATE` — Mandat de gestion locative
   */
  contractType?: 'LEASE' | 'SALE' | 'RENT_TO_OWN' | 'RESERVATION' | 'MANDATE';

  /**
   * Montant de la caution (XOF) — LEASE et RENT_TO_OWN
   */
  depositAmount?: number;

  /**
   * Date de fin du contrat.
   * - `LEASE` : null = durée indéterminée
   * - `RENT_TO_OWN` : **obligatoire** — détermine la durée du programme (ex. 2031-06-01 pour 5 ans)
   * - `SALE` / `MANDATE` : optionnel
   */
  endDate?: string;

  /**
   * Charges mensuelles (XOF) — LEASE uniquement
   */
  monthlyCharges?: number;

  /**
   * Mensualité versée vers l'acquisition du bien (XOF) — **RENT_TO_OWN uniquement**.
   * Exemple : bien à 12 000 000 XOF sur 60 mois → monthlyInstallment = 200 000 XOF
   */
  monthlyInstallment?: number;

  /**
   * Loyer mensuel hors charges (XOF) — LEASE uniquement
   */
  monthlyRent?: number;

  /**
   * Identifiant du propriétaire (User)
   */
  ownerId: string;

  /**
   * Jour du mois pour l'échéance du loyer (1-28, défaut: 5)
   */
  paymentDay?: number;

  /**
   * Identifiant du bien immobilier
   */
  propertyId: string;

  /**
   * Acompte de réservation (XOF) — RESERVATION uniquement
   */
  reservationDeposit?: number;

  /**
   * Durée de réservation en jours — RESERVATION uniquement
   */
  reservationDurationDays?: number;

  /**
   * Prix total du bien (XOF).
   * - `SALE` : prix de cession
   * - `RENT_TO_OWN` : valeur totale à acquérir (monthlyInstallment × durée = salePrice idéalement)
   */
  salePrice?: number;

  /**
   * Clauses particulières du contrat
   */
  specialClauses?: string;

  /**
   * Date de début du contrat
   */
  startDate: string;

  /**
   * Identifiant du dossier locataire (requis pour LEASE et RENT_TO_OWN)
   */
  tenantId?: string;

  /**
   * Conditions de résiliation anticipée
   */
  terminationConditions?: string;
}
