/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Demande de visite d'un bien
 */
export interface CreateVisitRequestDto {

  /**
   * Notes du client (optionnel)
   */
  clientNotes?: string;

  /**
   * ID du bien à visiter
   */
  propertyId: string;

  /**
   * Date de visite souhaitée (YYYY-MM-DD)
   */
  requestedDate: string;

  /**
   * Créneau horaire demandé
   */
  requestedTimeSlot?: string;
}
