/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateContractRequest {

  /**
   * Taux de commission agence (%)
   */
  agencyCommissionRate?: number;

  /**
   * Type de contrat
   */
  contractType?: 'LEASE' | 'SALE' | 'RESERVATION' | 'MANDATE';

  /**
   * Montant de la caution (XOF)
   */
  depositAmount?: number;

  /**
   * Date de fin du contrat (null = durée indéterminée)
   */
  endDate?: string;

  /**
   * Charges mensuelles (XOF) — LEASE uniquement
   */
  monthlyCharges?: number;

  /**
   * Loyer mensuel hors charges (XOF) — LEASE uniquement
   */
  monthlyRent?: number;

  /**
   * Identifiant du propriétaire (User)
   */
  ownerId: string;

  /**
   * Jour du mois pour l'échéance du loyer (1-28, défaut: 5)
   */
  paymentDay?: number;

  /**
   * Identifiant du bien immobilier
   */
  propertyId: string;

  /**
   * Acompte de réservation (XOF) — RESERVATION uniquement
   */
  reservationDeposit?: number;

  /**
   * Durée de réservation en jours — RESERVATION uniquement
   */
  reservationDurationDays?: number;

  /**
   * Prix de vente (XOF) — SALE uniquement
   */
  salePrice?: number;

  /**
   * Clauses particulières du contrat
   */
  specialClauses?: string;

  /**
   * Date de début du contrat
   */
  startDate: string;

  /**
   * Identifiant du dossier locataire (requis pour LEASE)
   */
  tenantId?: string;

  /**
   * Conditions de résiliation anticipée
   */
  terminationConditions?: string;
}
