/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Requête de création d'une réservation
 */
export interface CreateReservationRequest {

  /**
   * Date d'arrivée (incluse)
   */
  checkInDate: string;

  /**
   * Date de départ (exclue)
   */
  checkOutDate: string;

  /**
   * Nombre de voyageurs
   */
  guestCount: number;

  /**
   * Notes ou demandes spéciales du client
   */
  notes?: string;

  /**
   * UUID du bien à réserver
   */
  propertyId: string;
}
