/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateAdminRequest {
  email?: string;
  firstName?: string;
  lastName?: string;
  phone?: string;
  role: 'CLIENT' | 'OWNER' | 'ADMIN' | 'SUPER_ADMIN' | 'PARTNER';
}
