/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateMandateRequest {
  commissionRate?: number;
  endDate?: string;
  ownerId: string;
  specialClauses?: string;
  startDate: string;
  terminationConditions?: string;
}
