/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Hôtel partenaire disponible sur la plateforme UBAX
 */
export interface HotelResponse {

  /**
   * Adresse
   */
  address?: string;

  /**
   * Ville
   */
  city?: string;

  /**
   * Code pays ISO 3166-1 alpha-2
   */
  country?: string;

  /**
   * Description de l'hôtel
   */
  description?: string;

  /**
   * Email
   */
  email?: string;

  /**
   * Identifiant unique de l'hôtel
   */
  id?: string;

  /**
   * URL du logo
   */
  logoUrl?: string;

  /**
   * Nom de l'hôtel
   */
  name?: string;

  /**
   * Téléphone
   */
  phone?: string;

  /**
   * Nombre d'étoiles (1-5)
   */
  stars?: number;

  /**
   * Nombre total de chambres
   */
  totalRooms?: number;

  /**
   * Hôtel certifié par UBAX
   */
  verified?: boolean;

  /**
   * Site web
   */
  website?: string;
}
