/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ApplicationStatusLogResponse } from '../models/application-status-log-response';
export interface PartnerApplicationResponse {
  bailUrl?: string;
  city?: string;
  companyName?: string;
  country?: string;
  createdAt?: string;
  description?: string;
  dfeUrl?: string;
  email?: string;
  id?: string;
  latitude?: number;
  legalRepresentative?: string;
  legalStatus?: string;
  logoUrl?: string;
  longitude?: number;
  partnerType?: string;
  phone?: string;
  postalAddress?: string;
  rccmUrl?: string;
  registrationNumber?: string;
  rejectionReason?: string;
  reviewedAt?: string;
  reviewedByName?: string;
  status?: 'PENDING' | 'UNDER_REVIEW' | 'INCOMPLETE' | 'APPROVED' | 'REJECTED';
  statusHistory?: Array<ApplicationStatusLogResponse>;
  submittedAt?: string;
  updatedAt?: string;
  zone?: string;
}
