/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Requête de mise à jour du statut d'un paiement
 */
export interface PaymentStatusUpdateRequest {

  /**
   * Montant reçu (pour les paiements partiels)
   */
  amountPaid?: number;

  /**
   * Note libre
   */
  note?: string;

  /**
   * Date de réception effective
   */
  paidDate?: string;

  /**
   * Mode de paiement
   */
  paymentMethod?: 'CASH' | 'BANK_TRANSFER' | 'MOBILE_MONEY' | 'CHECK';

  /**
   * URL du reçu (si disponible)
   */
  receiptUrl?: string;

  /**
   * Nouveau statut
   */
  status: 'PENDING' | 'PAID' | 'LATE' | 'PARTIAL' | 'CANCELLED';
}
