/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PropertyDocumentAddRequest {
  docType?: string;
  fileName?: string;
  fileSize?: number;
  fileUrl?: string;
  mimeType?: string;
  title?: string;
  visibleToPublic?: boolean;
}
