/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PropertyAvailabilityResponse {
  availableUnits?: number;
  checkIn?: string;
  checkOut?: string;
  confirmedOverlaps?: number;
  propertyId?: string;
  unitCount?: number;
}
