/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Document légal associé à un bien immobilier
 */
export interface PropertyDocumentResponse {

  /**
   * Date de création
   */
  createdAt?: string;

  /**
   * Type de document : TITRE_FONCIER | PERMIS_CONSTRUIRE | DIAGNOSTIC | CONTRAT_BAIL | AUTRE
   */
  docType?: string;

  /**
   * Nom original du fichier
   */
  fileName?: string;

  /**
   * Taille du fichier en octets
   */
  fileSize?: number;

  /**
   * URL publique du fichier dans MinIO
   */
  fileUrl?: string;

  /**
   * Identifiant unique du document
   */
  id?: string;

  /**
   * Type MIME
   */
  mimeType?: string;

  /**
   * Identifiant du bien associé
   */
  propertyId?: string;

  /**
   * Titre descriptif du document
   */
  title?: string;

  /**
   * Date de dernière modification
   */
  updatedAt?: string;

  /**
   * Note du modérateur
   */
  verificationNote?: string;

  /**
   * Document vérifié par un modérateur
   */
  verified?: boolean;

  /**
   * Date de vérification
   */
  verifiedAt?: string;

  /**
   * Identifiant du modérateur ayant vérifié le document
   */
  verifiedById?: string;

  /**
   * Nom du modérateur
   */
  verifiedByName?: string;

  /**
   * Document visible aux acheteurs/locataires potentiels
   */
  visibleToPublic?: boolean;
}
