/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PropertyAmenityResponse } from '../models/property-amenity-response';

/**
 * Bien immobilier publié sur la plateforme UBAX
 */
export interface PropertyResponse {

  /**
   * Adresse complète du bien
   */
  address?: string;

  /**
   * Identifiant de l'agence gestionnaire (null si particulier)
   */
  agencyId?: string;

  /**
   * Nom de l'agence gestionnaire (null si particulier)
   */
  agencyName?: string;

  /**
   * Commodités du bien (standard + personnalisées)
   */
  amenities?: Array<PropertyAmenityResponse>;

  /**
   * Nombre de balcons/terrasses
   */
  balconies?: number;

  /**
   * Nombre de salles de bain
   */
  bathrooms?: number;

  /**
   * Type de lit principal (hôtel) : SINGLE, DOUBLE, TWIN, KING, QUEEN, BUNK
   */
  bedType?: string;

  /**
   * Nombre de chambres
   */
  bedrooms?: number;

  /**
   * Date d'expiration du boost
   */
  boostExpiresAt?: string;

  /**
   * Annonce boostée (mise en avant payante)
   */
  boosted?: boolean;

  /**
   * Ville du bien
   */
  city?: string;

  /**
   * État général du bien (NEW, GOOD, RENOVATE)
   */
  condition?: string;

  /**
   * URL de la photo de couverture (null si aucun média uploadé)
   */
  coverPhotoUrl?: string;

  /**
   * Date de création
   */
  createdAt?: string;

  /**
   * Description complète du bien
   */
  description?: string;

  /**
   * Quartier ou commune
   */
  district?: string;

  /**
   * Étage du bien (0 = RDC, null = villa/terrain)
   */
  floor?: number;

  /**
   * Identifiant de l'hôtel propriétaire (null si bien immobilier classique)
   */
  hotelId?: string;

  /**
   * Nom de l'hôtel propriétaire (null si bien immobilier classique)
   */
  hotelName?: string;

  /**
   * Identifiant unique du bien
   */
  id?: string;

  /**
   * Latitude GPS
   */
  latitude?: number;

  /**
   * Longitude GPS
   */
  longitude?: number;

  /**
   * Capacité maximale d'accueil (hôtel)
   */
  maxOccupancy?: number;

  /**
   * Formule repas (hôtel) : ROOM_ONLY, BREAKFAST, HALF_BOARD, FULL_BOARD, ALL_INCLUSIVE
   */
  mealPlan?: string;

  /**
   * Identifiant du propriétaire ou agent
   */
  ownerId?: string;

  /**
   * Nom complet du propriétaire ou agent
   */
  ownerName?: string;

  /**
   * Fréquence de facturation (hôtel) : NIGHTLY, WEEKLY, MONTHLY
   */
  paymentFrequency?: string;

  /**
   * Prix de vente ou loyer mensuel en XOF
   */
  price?: number;

  /**
   * Type de bien (APARTMENT, VILLA, HOUSE, LAND, OFFICE…)
   */
  propertyType?: string;

  /**
   * Date de publication de l'annonce
   */
  publishedAt?: string;

  /**
   * Motif de refus par le modérateur
   */
  rejectionReason?: string;

  /**
   * Nombre total de pièces principales
   */
  rooms?: number;

  /**
   * Statut de l'annonce dans son cycle de publication
   */
  status?: 'DRAFT' | 'PENDING' | 'PUBLISHED' | 'RESERVED' | 'SOLD' | 'ARCHIVED' | 'REJECTED';

  /**
   * Nom de la rue
   */
  street?: string;

  /**
   * Surface habitable nette (m²)
   */
  surfaceLiving?: number;

  /**
   * Surface totale du terrain (m²)
   */
  surfaceTotal?: number;

  /**
   * Titre accrocheur de l'annonce
   */
  title?: string;

  /**
   * Nombre total d'étages de l'immeuble
   */
  totalFloors?: number;

  /**
   * Type de transaction (SALE, RENT, RENT_FURNISHED, SHORT_STAY)
   */
  transactionType?: string;

  /**
   * Date de dernière modification
   */
  updatedAt?: string;

  /**
   * Année de construction
   */
  yearBuilt?: number;
}
