/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PropertyResponse {
  acceptsPets?: boolean;
  address?: string;
  agencyId?: string;
  agencyName?: string;
  balconies?: number;
  bathrooms?: number;
  bedrooms?: number;
  boostExpiresAt?: string;
  boosted?: boolean;
  city?: string;
  condition?: string;
  createdAt?: string;
  description?: string;
  district?: string;
  floor?: number;
  furnished?: boolean;
  hasAc?: boolean;
  hasElevator?: boolean;
  hasGarden?: boolean;
  hasGenerator?: boolean;
  hasParking?: boolean;
  hasPool?: boolean;
  hasSecurity?: boolean;
  hasWaterTank?: boolean;
  id?: string;
  latitude?: number;
  longitude?: number;
  ownerId?: string;
  ownerName?: string;
  pmrAccessible?: boolean;
  price?: number;
  propertyType?: string;
  publishedAt?: string;
  rejectionReason?: string;
  rooms?: number;
  status?: 'DRAFT' | 'PENDING' | 'PUBLISHED' | 'RESERVED' | 'SOLD' | 'ARCHIVED' | 'REJECTED';
  street?: string;
  surfaceLiving?: number;
  surfaceTotal?: number;
  title?: string;
  totalFloors?: number;
  transactionType?: string;
  updatedAt?: string;
  yearBuilt?: number;
}
