/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Requête d'ajout d'un document légal à un bien. Le fichier doit être préalablement uploadé dans MinIO via l'URL presignée.
 */
export interface PropertyDocumentAddRequest {

  /**
   * Type de document — valeurs depuis GET /v1/code-list/type/PROPERTY_DOCUMENT_TYPE : TITLE_DEED | BUILDING_PERMIT | DIAGNOSTIC | CADASTRAL_PLAN | INSURANCE | CONFORMITY_CERTIFICATE | OTHER
   */
  docType?: string;

  /**
   * Nom original du fichier
   */
  fileName?: string;

  /**
   * Taille du fichier en octets
   */
  fileSize?: number;

  /**
   * URL publique du fichier dans MinIO (retournée par l'endpoint presign)
   */
  fileUrl?: string;

  /**
   * Type MIME du fichier
   */
  mimeType?: string;

  /**
   * Titre descriptif du document
   */
  title?: string;

  /**
   * Rendre le document visible aux acheteurs/locataires potentiels
   */
  visibleToPublic?: boolean;
}
