/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Commodité d'un bien — standard (code) ou personnalisée (customValue)
 */
export interface PropertyAmenityRequest {

  /**
   * Code d'une commodité standard issue de la liste PROPERTY_AMENITY. Null si commodité personnalisée.
   */
  code?: string;

  /**
   * Description libre de la commodité personnalisée.
   */
  customDescription?: string;

  /**
   * Libellé d'une commodité non présente dans la liste standard. Null si code renseigné.
   */
  customValue?: string;
}
