/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PropertyAmenityRequest } from '../models/property-amenity-request';

/**
 * Requête de création d'un bien immobilier (statut DRAFT)
 */
export interface PropertyCreateRequest {

  /**
   * Adresse complète
   */
  address?: string;

  /**
   * Liste des commodités. Chaque entrée est soit un code standard (ex: POOL, AC, PARKING) soit une commodité personnalisée (customValue + customDescription).
   */
  amenities?: Array<PropertyAmenityRequest>;

  /**
   * Nombre de balcons/terrasses
   */
  balconies?: number;

  /**
   * Nombre de salles de bain
   */
  bathrooms?: number;

  /**
   * Type de lit (hôtel) : SINGLE, DOUBLE, TWIN, KING, QUEEN, BUNK
   */
  bedType?: string;

  /**
   * Nombre de chambres
   */
  bedrooms?: number;

  /**
   * Ville du bien
   */
  city?: string;

  /**
   * État général du bien (NEW, GOOD, RENOVATE)
   */
  condition?: string;

  /**
   * Description complète du bien
   */
  description?: string;

  /**
   * Quartier ou commune
   */
  district?: string;

  /**
   * Étage du bien (0 = RDC, null = villa/terrain)
   */
  floor?: number;

  /**
   * Latitude GPS
   */
  latitude?: number;

  /**
   * Longitude GPS
   */
  longitude?: number;

  /**
   * Capacité maximale d'accueil (hôtel)
   */
  maxOccupancy?: number;

  /**
   * Formule repas (hôtel) : ROOM_ONLY, BREAKFAST, HALF_BOARD, FULL_BOARD, ALL_INCLUSIVE
   */
  mealPlan?: string;

  /**
   * UUID du propriétaire réel du bien. Optionnel : si absent, l'appelant est le propriétaire.
   */
  ownerId?: string;

  /**
   * Fréquence de facturation (hôtel) : NIGHTLY, WEEKLY, MONTHLY
   */
  paymentFrequency?: string;

  /**
   * Prix de vente ou loyer mensuel en XOF
   */
  price: number;

  /**
   * Type de bien (ex : APARTMENT, VILLA, HOTEL_ROOM…)
   */
  propertyType?: string;

  /**
   * Nombre total de pièces principales
   */
  rooms?: number;

  /**
   * Nom de la rue
   */
  street?: string;

  /**
   * Surface habitable nette (m²)
   */
  surfaceLiving?: number;

  /**
   * Surface totale du terrain (m²)
   */
  surfaceTotal?: number;

  /**
   * Titre accrocheur de l'annonce
   */
  title?: string;

  /**
   * Nombre total d'étages de l'immeuble
   */
  totalFloors?: number;

  /**
   * Type de transaction (SALE, RENT, RENT_FURNISHED, SHORT_STAY)
   */
  transactionType?: string;

  /**
   * Année de construction
   */
  yearBuilt?: number;
}
