/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Commodité associée à un bien immobilier
 */
export interface PropertyAmenityResponse {

  /**
   * Code commodité standard (null si personnalisée)
   */
  code?: string;

  /**
   * Description de la commodité personnalisée
   */
  customDescription?: string;

  /**
   * Libellé personnalisé (null si commodité standard)
   */
  customValue?: string;

  /**
   * Identifiant unique de la commodité
   */
  id?: string;
}
