/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PropertyDocumentResponse {
  createdAt?: string;
  docType?: string;
  fileName?: string;
  fileSize?: number;
  fileUrl?: string;
  id?: string;
  mimeType?: string;
  propertyId?: string;
  title?: string;
  updatedAt?: string;
  verificationNote?: string;
  verified?: boolean;
  verifiedAt?: string;
  verifiedById?: string;
  verifiedByName?: string;
  visibleToPublic?: boolean;
}
