/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Rejet d'une demande de visite par l'agence
 */
export interface RejectVisitRequestDto {

  /**
   * Motif du rejet
   */
  reason?: string;
}
