/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ScheduleInterventionRequest {

  /**
   * Date et heure planifiées pour l'intervention
   */
  interventionScheduledAt: string;

  /**
   * Nom du prestataire ou technicien mandaté
   */
  technicianName?: string;

  /**
   * Numéro international du technicien
   */
  technicianPhone?: string;
}
