/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface StorageUploadResponse {
  bucket?: string;
  fileName?: string;
  fileSize?: number;
  fileUrl?: string;
  mimeType?: string;
  objectName?: string;
}
