/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TenantCreateRequest {
  addressProofUrl?: string;
  employerName?: string;
  employmentStatus?: string;
  guarantorEmail?: string;
  guarantorName?: string;
  guarantorPhone?: string;
  hasGuarantor?: boolean;
  idDocumentExpiry?: string;
  idDocumentNumber?: string;
  idDocumentType?: string;
  idDocumentUrl?: string;
  incomeProofUrl?: string;
  monthlyIncome?: number;
  propertyId: string;
}
