/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TicketAttachmentInput {

  /**
   * Catégorie (défaut : INCIDENT_PHOTO)
   */
  attachmentType?: 'INCIDENT_PHOTO' | 'INCIDENT_VIDEO' | 'INTERVENTION_REPORT' | 'INVOICE' | 'OTHER';

  /**
   * Légende courte
   */
  caption?: string;

  /**
   * Nom original du fichier
   */
  fileName?: string;

  /**
   * Taille en octets
   */
  fileSize?: number;

  /**
   * URL MinIO du fichier pré-uploadé (bucket ticket-attachments)
   */
  fileUrl?: string;

  /**
   * Type MIME
   */
  mimeType?: string;
}
