/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateTicketStatusRequest {

  /**
   * Note de résolution — obligatoire pour RESOLVED et CLOSED
   */
  resolutionNote?: string;

  /**
   * Nouveau statut du ticket
   */
  status?: 'IN_ANALYSIS' | 'TECHNICIAN_SENT' | 'RESOLVED' | 'CLOSED' | 'CANCELLED';
}
