/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Mise à jour des dates fermées (blackout)
 */
export interface UpdateBlackoutDatesDto {

  /**
   * Liste des dates fermées au format YYYY-MM-DD
   */
  blackoutDates: Array<string>;
}
