/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserSubRoleResponse {
  createdAt?: string;
  id?: string;
  role?: string;
  scope?: 'UBAX_INTERNAL' | 'AGENCE' | 'HOTEL';
  userId?: string;
}
