/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * État d'une demande de visite
 */
export interface VisitRequestResponse {

  /**
   * ID de l'agent assigné (optionnel)
   */
  agentId?: string;

  /**
   * Nom de l'agent (optionnel)
   */
  agentName?: string;

  /**
   * ID du client demandeur
   */
  clientId?: string;

  /**
   * Nom du client
   */
  clientName?: string;

  /**
   * Notes du client
   */
  clientNotes?: string;

  /**
   * Date confirmée par l'agence (si confirmée)
   */
  confirmedDate?: string;

  /**
   * Créneau confirmé par l'agence (si confirmée)
   */
  confirmedTimeSlot?: string;

  /**
   * Date de création
   */
  createdAt?: string;

  /**
   * ID unique de la demande
   */
  id?: string;

  /**
   * ID du bien
   */
  propertyId?: string;

  /**
   * Titre du bien
   */
  propertyTitle?: string;

  /**
   * Motif du rejet (si rejetée)
   */
  rejectionReason?: string;

  /**
   * Date demandée
   */
  requestedDate?: string;

  /**
   * Créneau horaire demandé
   */
  requestedTimeSlot?: string;

  /**
   * Statut actuel
   */
  status?: 'PENDING' | 'CONFIRMED' | 'REJECTED' | 'CANCELLED' | 'COMPLETED';

  /**
   * Date de dernière modification
   */
  updatedAt?: string;
}
