/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AvailableSlot } from '../models/available-slot';

/**
 * Créneaux disponibles pour les visites d'un bien
 */
export interface VisitAvailabilityResponse {

  /**
   * Dates disponibles pour les 30 prochains jours
   */
  availableDates?: Array<string>;

  /**
   * ID du bien
   */
  propertyId?: string;

  /**
   * Créneaux disponibles par date. Chaque créneau indique le nombre de places disponibles.
   */
  slotsByDate?: {
[key: string]: Array<AvailableSlot>;
};
}
