/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PropertyMediaAddRequest } from '../../models/property-media-add-request';
import { PropertyMediaResponse } from '../../models/property-media-response';

export interface AddMedia$Params {
  id: string;
      body: PropertyMediaAddRequest
}

export function addMedia(http: HttpClient, rootUrl: string, params: AddMedia$Params, context?: HttpContext): Observable<StrictHttpResponse<PropertyMediaResponse>> {
  const rb = new RequestBuilder(rootUrl, addMedia.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PropertyMediaResponse>;
    })
  );
}

addMedia.PATH = '/v1/properties/{id}/media';
