/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PropertyDocumentAddRequest } from '../../models/property-document-add-request';
import { PropertyDocumentResponse } from '../../models/property-document-response';

export interface AddDocument$Params {
  id: string;
      body: PropertyDocumentAddRequest
}

export function addDocument(http: HttpClient, rootUrl: string, params: AddDocument$Params, context?: HttpContext): Observable<StrictHttpResponse<PropertyDocumentResponse>> {
  const rb = new RequestBuilder(rootUrl, addDocument.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PropertyDocumentResponse>;
    })
  );
}

addDocument.PATH = '/v1/properties/{id}/documents';
