/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PropertyAvailabilityResponse } from '../../models/property-availability-response';

export interface GetAvailability$Params {
  id: string;

/**
 * Date d'arrivée (YYYY-MM-DD)
 */
  checkIn: string;

/**
 * Date de départ (YYYY-MM-DD)
 */
  checkOut: string;
}

export function getAvailability(http: HttpClient, rootUrl: string, params: GetAvailability$Params, context?: HttpContext): Observable<StrictHttpResponse<PropertyAvailabilityResponse>> {
  const rb = new RequestBuilder(rootUrl, getAvailability.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
    rb.query('checkIn', params.checkIn, {});
    rb.query('checkOut', params.checkOut, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PropertyAvailabilityResponse>;
    })
  );
}

getAvailability.PATH = '/v1/properties/{id}/availability';
