/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Pageable } from '../../models/pageable';
import { PropertyResponse } from '../../models/property-response';

export interface List1$Params {
  status?: 'DRAFT' | 'PENDING' | 'PUBLISHED' | 'RESERVED' | 'SOLD' | 'ARCHIVED' | 'REJECTED';
  city?: string;
  propertyType?: string;
  transactionType?: string;
  minPrice?: number;
  maxPrice?: number;
  agencyId?: string;
  ownerId?: string;
  pageable: Pageable;
}

export function list1(http: HttpClient, rootUrl: string, params: List1$Params, context?: HttpContext): Observable<StrictHttpResponse<PropertyResponse>> {
  const rb = new RequestBuilder(rootUrl, list1.PATH, 'get');
  if (params) {
    rb.query('status', params.status, {});
    rb.query('city', params.city, {});
    rb.query('propertyType', params.propertyType, {});
    rb.query('transactionType', params.transactionType, {});
    rb.query('minPrice', params.minPrice, {});
    rb.query('maxPrice', params.maxPrice, {});
    rb.query('agencyId', params.agencyId, {});
    rb.query('ownerId', params.ownerId, {});
    rb.query('pageable', params.pageable, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PropertyResponse>;
    })
  );
}

list1.PATH = '/v1/properties';
