/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Pageable } from '../../models/pageable';
import { PropertyResponse } from '../../models/property-response';

export interface ListHotelProperties$Params {

/**
 * Filtre par statut (null = tous les statuts)
 */
  status?: 'DRAFT' | 'PENDING' | 'PUBLISHED' | 'RESERVED' | 'SOLD' | 'ARCHIVED' | 'REJECTED';

/**
 * Restreindre à un hôtel précis (UUID)
 */
  hotelId?: string;
  pageable: Pageable;

/**
 * Numéro de page (0-based)
 */
  page?: number;

/**
 * Nombre de résultats par page (max 200)
 */
  size?: number;

/**
 * Tri : champ,direction — ex: `createdAt,desc` · `price,asc`
 */
  sort?: string;
}

export function listHotelProperties(http: HttpClient, rootUrl: string, params: ListHotelProperties$Params, context?: HttpContext): Observable<StrictHttpResponse<PropertyResponse>> {
  const rb = new RequestBuilder(rootUrl, listHotelProperties.PATH, 'get');
  if (params) {
    rb.query('status', params.status, {});
    rb.query('hotelId', params.hotelId, {});
    rb.query('pageable', params.pageable, {});
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
    rb.query('sort', params.sort, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PropertyResponse>;
    })
  );
}

listHotelProperties.PATH = '/v1/properties/admin/hotels';
