/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Pageable } from '../../models/pageable';
import { PropertyResponse } from '../../models/property-response';

export interface List2$Params {

/**
 * Statut des biens (défaut : PUBLISHED). ADMIN requis pour tout autre statut.
 */
  status?: 'DRAFT' | 'PENDING' | 'PUBLISHED' | 'RESERVED' | 'SOLD' | 'ARCHIVED' | 'REJECTED';

/**
 * Filtre par ville (insensible à la casse)
 */
  city?: string;

/**
 * Filtre par type de bien (APARTMENT, VILLA, HOTEL_SUITE…)
 */
  propertyType?: string;

/**
 * Filtre par type de transaction (SALE, RENT, SHORT_STAY…)
 */
  transactionType?: string;

/**
 * Prix minimum en XOF
 */
  minPrice?: number;

/**
 * Prix maximum en XOF
 */
  maxPrice?: number;

/**
 * Filtre par agence immobilière (UUID)
 */
  agencyId?: string;

/**
 * Filtre par propriétaire / bailleur (UUID)
 */
  ownerId?: string;

/**
 * Filtre par hôtel – retourne uniquement les chambres/suites de cet hôtel (UUID)
 */
  hotelId?: string;
  pageable: Pageable;

/**
 * Numéro de page (0-based)
 */
  page?: number;

/**
 * Nombre de résultats par page (max 200)
 */
  size?: number;

/**
 * Tri : champ,direction — ex: `createdAt,desc` · `price,asc` · `publishedAt,desc`
 */
  sort?: string;
}

export function list2(http: HttpClient, rootUrl: string, params: List2$Params, context?: HttpContext): Observable<StrictHttpResponse<PropertyResponse>> {
  const rb = new RequestBuilder(rootUrl, list2.PATH, 'get');
  if (params) {
    rb.query('status', params.status, {});
    rb.query('city', params.city, {});
    rb.query('propertyType', params.propertyType, {});
    rb.query('transactionType', params.transactionType, {});
    rb.query('minPrice', params.minPrice, {});
    rb.query('maxPrice', params.maxPrice, {});
    rb.query('agencyId', params.agencyId, {});
    rb.query('ownerId', params.ownerId, {});
    rb.query('hotelId', params.hotelId, {});
    rb.query('pageable', params.pageable, {});
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
    rb.query('sort', params.sort, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PropertyResponse>;
    })
  );
}

list2.PATH = '/v1/properties';
