/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PropertyDocumentResponse } from '../../models/property-document-response';

export interface ListDocuments$Params {
  id: string;
}

export function listDocuments(http: HttpClient, rootUrl: string, params: ListDocuments$Params, context?: HttpContext): Observable<StrictHttpResponse<PropertyDocumentResponse>> {
  const rb = new RequestBuilder(rootUrl, listDocuments.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PropertyDocumentResponse>;
    })
  );
}

listDocuments.PATH = '/v1/properties/{id}/documents';
