/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PropertyMediaResponse } from '../../models/property-media-response';

export interface ListMedia$Params {
  id: string;
}

export function listMedia(http: HttpClient, rootUrl: string, params: ListMedia$Params, context?: HttpContext): Observable<StrictHttpResponse<PropertyMediaResponse>> {
  const rb = new RequestBuilder(rootUrl, listMedia.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PropertyMediaResponse>;
    })
  );
}

listMedia.PATH = '/v1/properties/{id}/media';
