/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Pageable } from '../../models/pageable';
import { PropertyResponse } from '../../models/property-response';

export interface ListMine$Params {
  status?: 'DRAFT' | 'PENDING' | 'PUBLISHED' | 'RESERVED' | 'SOLD' | 'ARCHIVED' | 'REJECTED';
  pageable: Pageable;
}

export function listMine(http: HttpClient, rootUrl: string, params: ListMine$Params, context?: HttpContext): Observable<StrictHttpResponse<PropertyResponse>> {
  const rb = new RequestBuilder(rootUrl, listMine.PATH, 'get');
  if (params) {
    rb.query('status', params.status, {});
    rb.query('pageable', params.pageable, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PropertyResponse>;
    })
  );
}

listMine.PATH = '/v1/properties/mine';
