/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PropertyResponse } from '../../models/property-response';

export interface RemoveBoost$Params {
  id: string;
}

export function removeBoost(http: HttpClient, rootUrl: string, params: RemoveBoost$Params, context?: HttpContext): Observable<StrictHttpResponse<PropertyResponse>> {
  const rb = new RequestBuilder(rootUrl, removeBoost.PATH, 'delete');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PropertyResponse>;
    })
  );
}

removeBoost.PATH = '/v1/properties/{id}/boost';
