/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PropertyMediaResponse } from '../../models/property-media-response';

export interface SetCover$Params {
  id: string;
  mediaId: string;
}

export function setCover(http: HttpClient, rootUrl: string, params: SetCover$Params, context?: HttpContext): Observable<StrictHttpResponse<PropertyMediaResponse>> {
  const rb = new RequestBuilder(rootUrl, setCover.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.path('mediaId', params.mediaId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PropertyMediaResponse>;
    })
  );
}

setCover.PATH = '/v1/properties/{id}/media/{mediaId}/cover';
