/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PropertyResponse } from '../../models/property-response';
import { PropertyStatusUpdateRequest } from '../../models/property-status-update-request';

export interface UpdateStatus1$Params {
  id: string;
      body: PropertyStatusUpdateRequest
}

export function updateStatus1(http: HttpClient, rootUrl: string, params: UpdateStatus1$Params, context?: HttpContext): Observable<StrictHttpResponse<PropertyResponse>> {
  const rb = new RequestBuilder(rootUrl, updateStatus1.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PropertyResponse>;
    })
  );
}

updateStatus1.PATH = '/v1/properties/{id}/status';
