/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PropertyMediaResponse } from '../../models/property-media-response';

export interface UploadMedia$Params {
  id: string;

/**
 * Type de média : PHOTO, VIDEO, PLAN
 */
  mediaType?: string;

/**
 * Définir comme photo de couverture
 */
  cover?: boolean;
      body?: {

/**
 * Fichier image ou vidéo (JPEG, PNG, WEBP, MP4, MOV)
 */
'file': Blob;
}
}

export function uploadMedia(http: HttpClient, rootUrl: string, params: UploadMedia$Params, context?: HttpContext): Observable<StrictHttpResponse<PropertyMediaResponse>> {
  const rb = new RequestBuilder(rootUrl, uploadMedia.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
    rb.query('mediaType', params.mediaType, {});
    rb.query('cover', params.cover, {});
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PropertyMediaResponse>;
    })
  );
}

uploadMedia.PATH = '/v1/properties/{id}/media/upload';
