/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PropertyDocumentResponse } from '../../models/property-document-response';

export interface VerifyDocument$Params {
  id: string;
  docId: string;

/**
 * Commentaire optionnel de vérification
 */
  note?: string;
}

export function verifyDocument(http: HttpClient, rootUrl: string, params: VerifyDocument$Params, context?: HttpContext): Observable<StrictHttpResponse<PropertyDocumentResponse>> {
  const rb = new RequestBuilder(rootUrl, verifyDocument.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.path('docId', params.docId, {});
    rb.query('note', params.note, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PropertyDocumentResponse>;
    })
  );
}

verifyDocument.PATH = '/v1/properties/{id}/documents/{docId}/verify';
