/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AssignSubRolesRequest } from '../../models/assign-sub-roles-request';
import { CustomResponse } from '../../models/custom-response';

export interface AssignSubRoles2$Params {
  userId: string;
      body: AssignSubRolesRequest
}

export function assignSubRoles2(http: HttpClient, rootUrl: string, params: AssignSubRoles2$Params, context?: HttpContext): Observable<StrictHttpResponse<CustomResponse>> {
  const rb = new RequestBuilder(rootUrl, assignSubRoles2.PATH, 'post');
  if (params) {
    rb.path('userId', params.userId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CustomResponse>;
    })
  );
}

assignSubRoles2.PATH = '/v1/admin/users/{userId}/sub-roles';
