/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CustomResponse } from '../../models/custom-response';

export interface GetSubRoles2$Params {
  userId: string;

/**
 * Filtre par scope (optionnel)
 */
  scope?: 'UBAX_INTERNAL' | 'AGENCE' | 'HOTEL';
}

export function getSubRoles2(http: HttpClient, rootUrl: string, params: GetSubRoles2$Params, context?: HttpContext): Observable<StrictHttpResponse<CustomResponse>> {
  const rb = new RequestBuilder(rootUrl, getSubRoles2.PATH, 'get');
  if (params) {
    rb.path('userId', params.userId, {});
    rb.query('scope', params.scope, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CustomResponse>;
    })
  );
}

getSubRoles2.PATH = '/v1/admin/users/{userId}/sub-roles';
