/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CustomResponse } from '../../models/custom-response';

export interface AssignAgent$Params {

/**
 * ID de la demande
 */
  visitRequestId: string;

/**
 * ID de l'agent
 */
  agentId: string;
}

export function assignAgent(http: HttpClient, rootUrl: string, params: AssignAgent$Params, context?: HttpContext): Observable<StrictHttpResponse<CustomResponse>> {
  const rb = new RequestBuilder(rootUrl, assignAgent.PATH, 'patch');
  if (params) {
    rb.path('visitRequestId', params.visitRequestId, {});
    rb.path('agentId', params.agentId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CustomResponse>;
    })
  );
}

assignAgent.PATH = '/v1/agency/property-visits/{visitRequestId}/assign-agent/{agentId}';
