/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ConfigureVisitAvailabilityDto } from '../../models/configure-visit-availability-dto';
import { CustomResponse } from '../../models/custom-response';

export interface ConfigureAvailability$Params {
      body: ConfigureVisitAvailabilityDto
}

export function configureAvailability(http: HttpClient, rootUrl: string, params: ConfigureAvailability$Params, context?: HttpContext): Observable<StrictHttpResponse<CustomResponse>> {
  const rb = new RequestBuilder(rootUrl, configureAvailability.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CustomResponse>;
    })
  );
}

configureAvailability.PATH = '/v1/agency/property-visits/config';
