/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { VisitAvailabilityResponse } from '../../models/visit-availability-response';

export interface GetConfiguration$Params {

/**
 * ID du bien immobilier
 */
  propertyId: string;
}

export function getConfiguration(http: HttpClient, rootUrl: string, params: GetConfiguration$Params, context?: HttpContext): Observable<StrictHttpResponse<VisitAvailabilityResponse>> {
  const rb = new RequestBuilder(rootUrl, getConfiguration.PATH, 'get');
  if (params) {
    rb.path('propertyId', params.propertyId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<VisitAvailabilityResponse>;
    })
  );
}

getConfiguration.PATH = '/v1/agency/property-visits/config/{propertyId}';
