/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CustomResponse } from '../../models/custom-response';
import { RejectVisitRequestDto } from '../../models/reject-visit-request-dto';

export interface RejectRequest$Params {

/**
 * ID de la demande
 */
  visitRequestId: string;
      body: RejectVisitRequestDto
}

export function rejectRequest(http: HttpClient, rootUrl: string, params: RejectRequest$Params, context?: HttpContext): Observable<StrictHttpResponse<CustomResponse>> {
  const rb = new RequestBuilder(rootUrl, rejectRequest.PATH, 'patch');
  if (params) {
    rb.path('visitRequestId', params.visitRequestId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CustomResponse>;
    })
  );
}

rejectRequest.PATH = '/v1/agency/property-visits/{visitRequestId}/reject';
