/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CustomResponse } from '../../models/custom-response';
import { UpdateBlackoutDatesDto } from '../../models/update-blackout-dates-dto';

export interface UpdateBlackoutDates$Params {

/**
 * ID du bien
 */
  propertyId: string;
      body: UpdateBlackoutDatesDto
}

export function updateBlackoutDates(http: HttpClient, rootUrl: string, params: UpdateBlackoutDates$Params, context?: HttpContext): Observable<StrictHttpResponse<CustomResponse>> {
  const rb = new RequestBuilder(rootUrl, updateBlackoutDates.PATH, 'put');
  if (params) {
    rb.path('propertyId', params.propertyId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CustomResponse>;
    })
  );
}

updateBlackoutDates.PATH = '/v1/agency/property-visits/config/{propertyId}/blackout-dates';
