/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AdminAgencyResponse } from '../../models/admin-agency-response';

export interface ActivateAgency$Params {
  id: string;
}

export function activateAgency(http: HttpClient, rootUrl: string, params: ActivateAgency$Params, context?: HttpContext): Observable<StrictHttpResponse<AdminAgencyResponse>> {
  const rb = new RequestBuilder(rootUrl, activateAgency.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AdminAgencyResponse>;
    })
  );
}

activateAgency.PATH = '/v1/admin/partners/agencies/{id}/activate';
