/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AdminHotelResponse } from '../../models/admin-hotel-response';
import { UpdateSubscriptionRequest } from '../../models/update-subscription-request';

export interface UpdateHotelSubscription$Params {
  id: string;
      body: UpdateSubscriptionRequest
}

export function updateHotelSubscription(http: HttpClient, rootUrl: string, params: UpdateHotelSubscription$Params, context?: HttpContext): Observable<StrictHttpResponse<AdminHotelResponse>> {
  const rb = new RequestBuilder(rootUrl, updateHotelSubscription.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AdminHotelResponse>;
    })
  );
}

updateHotelSubscription.PATH = '/v1/admin/partners/hotels/{id}/subscription';
