/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BailleurAgencyResponse } from '../../models/bailleur-agency-response';

export interface GetMyAgencies$Params {
}

export function getMyAgencies(http: HttpClient, rootUrl: string, params?: GetMyAgencies$Params, context?: HttpContext): Observable<StrictHttpResponse<BailleurAgencyResponse>> {
  const rb = new RequestBuilder(rootUrl, getMyAgencies.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<BailleurAgencyResponse>;
    })
  );
}

getMyAgencies.PATH = '/v1/bailleur/my-agencies';
