/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Pageable } from '../../models/pageable';
import { PaymentResponse } from '../../models/payment-response';

export interface List2$Params {
  status?: 'PENDING' | 'PAID' | 'LATE' | 'PARTIAL' | 'CANCELLED';
  type?: 'RENT' | 'DEPOSIT' | 'CHARGES' | 'COMMISSION' | 'SALE';
  propertyId?: string;
  contractId?: string;
  tenantId?: string;
  from?: string;
  to?: string;
  pageable: Pageable;
}

export function list2(http: HttpClient, rootUrl: string, params: List2$Params, context?: HttpContext): Observable<StrictHttpResponse<PaymentResponse>> {
  const rb = new RequestBuilder(rootUrl, list2.PATH, 'get');
  if (params) {
    rb.query('status', params.status, {});
    rb.query('type', params.type, {});
    rb.query('propertyId', params.propertyId, {});
    rb.query('contractId', params.contractId, {});
    rb.query('tenantId', params.tenantId, {});
    rb.query('from', params.from, {});
    rb.query('to', params.to, {});
    rb.query('pageable', params.pageable, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PaymentResponse>;
    })
  );
}

list2.PATH = '/v1/payments';
