/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AddTeamMemberRequest {
  email?: string;
  firstName?: string;
  lastName?: string;
  phone?: string;
  subRoles?: Array<string>;
}
