/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AdminUserResponse {
  email?: string;
  firstName?: string;
  keycloakId?: string;
  lastName?: string;
  phone?: string;
  roles?: Array<'CLIENT' | 'OWNER' | 'ADMIN' | 'SUPER_ADMIN' | 'PARTNER' | 'PARTNER_ADMIN'>;
  userId?: string;
}
