/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Bailleur lié à une agence — retourné par GET /v1/bailleur/agency/bailleurs
 */
export interface AgencyBailleurResponse {
  avatarUrl?: string;
  email?: string;
  firstName?: string;

  /**
   * UUID du compte bailleur — à utiliser comme `ownerId` dans POST /v1/properties
   */
  id?: string;

  /**
   * Date à laquelle le lien agence↔bailleur a été créé (approbation de la demande)
   */
  joinedAt?: string;
  lastName?: string;
  phone?: string;
}
