/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AssignTicketRequest {

  /**
   * Identifiant (DB) de l'agent SAV à qui assigner le ticket
   */
  assignedToId: string;
}
