/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BailleurPropertyResponse {
  address?: string;
  description?: string;
  desiredRent?: number;
  geoVerified?: boolean;
  id?: string;
  latitude?: number;
  longitude?: number;
  propertyType?: string;
  rooms?: number;
  surface?: number;
}
