/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BailleurPropertyResponse } from '../models/bailleur-property-response';
export interface BailleurApplicationResponse {
  agencyId?: string;
  agencyName?: string;
  conflictDetected?: boolean;
  conflictNote?: string;
  createdAt?: string;
  email?: string;
  firstName?: string;
  id?: string;
  idNumber?: string;
  idType?: string;
  lastName?: string;
  phone?: string;
  properties?: Array<BailleurPropertyResponse>;
  rejectionReason?: string;
  reviewedAt?: string;
  reviewedByName?: string;
  status?: 'PENDING' | 'APPROVED' | 'REJECTED' | 'CANCELLED';
  updatedAt?: string;
}
