/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BailleurApplicationResponse {
  agencyId?: string;
  agencyName?: string;
  createdAt?: string;
  description?: string;
  email?: string;
  firstName?: string;
  id?: string;
  idDocRectoUrl?: string;
  idDocVersoUrl?: string;
  idNumber?: string;
  idType?: string;
  lastName?: string;
  phone?: string;
  rejectionReason?: string;
  reviewedAt?: string;
  reviewedByName?: string;
  status?: 'PENDING' | 'APPROVED' | 'REJECTED' | 'CANCELLED';
  updatedAt?: string;
}
