/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BailleurApplyRequest {
  agencyId: string;

  /**
   * Description des biens et motivation de la demande d'adhésion à l'agence. Obligatoire — minimum 10 mots pour permettre à l'agence d'évaluer la demande.
   */
  description?: string;

  /**
   * Email de contact. Requis uniquement si le compte CLIENT ne possède pas d'adresse email.
   */
  email?: string;

  /**
   * URL de la photo recto de la pièce d'identité — obtenue via POST /v1/storage/upload?bucket=bailleur-documents
   */
  idDocRectoUrl?: string;

  /**
   * URL de la photo verso de la pièce d'identité — obtenue via POST /v1/storage/upload?bucket=bailleur-documents
   */
  idDocVersoUrl?: string;

  /**
   * Numéro de la pièce d'identité correspondant au type sélectionné
   */
  idNumber?: string;

  /**
   * Type de pièce d'identité — valeurs disponibles via GET /v1/code-list/type/ID_TYPE
   */
  idType?: 'CNI' | 'PASSEPORT' | 'PERMIS_CONDUIRE' | 'TITRE_SEJOUR' | 'CARTE_CONSULAIRE';
}
