/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateContractRequest {

  /**
   * Taux de commission agence (%)
   */
  agencyCommissionRate?: number;

  /**
   * Type de contrat :
   * - `LEASE` — Bail de location (tenantId + monthlyRent requis)
   * - `SALE` — Acte de vente (tenantId acheteur + salePrice requis)
   * - `RENT_TO_OWN` — Location-vente (tenantId + salePrice + monthlyInstallment + endDate ou durationYears requis)
   * - `RESERVATION` — Contrat de réservation (reservationDeposit requis)
   * ⚠️ `MANDATE` est bloqué — utiliser POST /v1/mandates
   */
  contractType?: 'LEASE' | 'SALE' | 'RENT_TO_OWN' | 'RESERVATION';

  /**
   * Montant de la caution (XOF) — LEASE et RENT_TO_OWN
   */
  depositAmount?: number;

  /**
   * Durée du programme RENT_TO_OWN en années (1-30).
   * Alternative à `endDate` : si les deux sont fournis, `endDate` est prioritaire.
   * Exemple : 5 ans → endDate calculée à startDate + 5 ans
   */
  durationYears?: number;

  /**
   * Date de fin du contrat.
   * - `LEASE` : null = durée indéterminée
   * - `RENT_TO_OWN` : optionnel si `durationYears` est fourni
   * - `SALE` / `MANDATE` : optionnel
   */
  endDate?: string;

  /**
   * Charges mensuelles (XOF) — LEASE uniquement
   */
  monthlyCharges?: number;

  /**
   * Mensualité versée vers l'acquisition du bien (XOF) — **RENT_TO_OWN uniquement**.
   * Exemple : bien à 12 000 000 XOF sur 60 mois → monthlyInstallment = 200 000 XOF
   */
  monthlyInstallment?: number;

  /**
   * Loyer mensuel hors charges (XOF) — LEASE uniquement
   */
  monthlyRent?: number;

  /**
   * Jour du mois pour l'échéance du loyer (1-28, défaut: 5)
   */
  paymentDay?: number;

  /**
   * Identifiant du bien immobilier
   */
  propertyId: string;

  /**
   * Acompte de réservation (XOF) — RESERVATION uniquement
   */
  reservationDeposit?: number;

  /**
   * Durée de réservation en jours — RESERVATION uniquement
   */
  reservationDurationDays?: number;

  /**
   * Prix total du bien (XOF).
   * - `SALE` : prix de cession
   * - `RENT_TO_OWN` : valeur totale à acquérir (monthlyInstallment × durée = salePrice idéalement)
   */
  salePrice?: number;

  /**
   * Clauses particulières du contrat
   */
  specialClauses?: string;

  /**
   * Date de début du contrat
   */
  startDate: string;

  /**
   * Identifiant du dossier locataire (requis pour LEASE, RENT_TO_OWN et SALE)
   */
  tenantId?: string;

  /**
   * Conditions de résiliation anticipée
   */
  terminationConditions?: string;
}
