/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Réponse d'une dépense comptable
 */
export interface ExpenseResponse {
  agencyId?: string;
  amount?: number;
  category?: 'MAINTENANCE' | 'MARKETING' | 'SALARY' | 'UTILITIES' | 'TAX' | 'OTHER';
  costCenter?: 'AGENCY_GENERAL' | 'PROPERTY_SPECIFIC';
  createdAt?: string;
  createdById?: string;
  createdByName?: string;
  expenseDate?: string;
  id?: string;
  invoiceReference?: string;
  justificationUrl?: string;
  label?: string;
  note?: string;
  paymentMethod?: 'CASH' | 'BANK_TRANSFER' | 'MOBILE_MONEY' | 'CHECK';
  propertyId?: string;
  provider?: string;
  updatedAt?: string;
}
