/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Requête de création d'une dépense comptable
 */
export interface ExpenseCreateRequest {

  /**
   * Montant en XOF
   */
  amount: number;

  /**
   * Catégorie de la dépense
   */
  category: 'MAINTENANCE' | 'MARKETING' | 'SALARY' | 'UTILITIES' | 'TAX' | 'OTHER';

  /**
   * Centre de coût
   */
  costCenter: 'AGENCY_GENERAL' | 'PROPERTY_SPECIFIC';

  /**
   * Date de la dépense (ISO-8601)
   */
  expenseDate: string;

  /**
   * Référence facture ou bon de commande
   */
  invoiceReference?: string;

  /**
   * URL de la facture déjà uploadée dans MinIO
   */
  justificationUrl?: string;

  /**
   * Intitulé de la dépense
   */
  label?: string;

  /**
   * Note libre
   */
  note?: string;

  /**
   * Mode de règlement
   */
  paymentMethod?: 'CASH' | 'BANK_TRANSFER' | 'MOBILE_MONEY' | 'CHECK';

  /**
   * UUID du bien concerné (requis si costCenter = PROPERTY_SPECIFIC)
   */
  propertyId?: string;

  /**
   * Nom du fournisseur ou prestataire
   */
  provider?: string;
}
