/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface LaCodeListDto {
  description?: string;
  id?: string;
  systemAssign?: boolean;
  type?: string;
  value?: string;
}
