/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface LoginResponse {
  access_token?: string;
  expires_in?: number;
  refresh_expires_in?: number;
  refresh_token?: string;
  scope?: string;
  session_state?: string;
  token_type?: string;
}
