/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Requête d'enregistrement d'un paiement
 */
export interface PaymentCreateRequest {

  /**
   * Montant total attendu (XOF)
   */
  amount: number;

  /**
   * Montant effectivement reçu – renseigné pour les paiements partiels
   */
  amountPaid?: number;

  /**
   * UUID du contrat lié (optionnel si hors contrat)
   */
  contractId?: string;

  /**
   * Date d'échéance (ISO-8601)
   */
  dueDate: string;

  /**
   * Note libre
   */
  note?: string;

  /**
   * Date de réception effective (null si pas encore encaissé)
   */
  paidDate?: string;

  /**
   * Mode de paiement
   */
  paymentMethod?: 'CASH' | 'BANK_TRANSFER' | 'MOBILE_MONEY' | 'CHECK';

  /**
   * Type de paiement
   */
  paymentType: 'RENT' | 'DEPOSIT' | 'CHARGES' | 'COMMISSION' | 'SALE';

  /**
   * Période couverte (libellé libre)
   */
  periodLabel?: string;

  /**
   * UUID du bien concerné (optionnel)
   */
  propertyId?: string;

  /**
   * URL du reçu déjà uploadé dans MinIO
   */
  receiptUrl?: string;

  /**
   * Référence interne du paiement (générée si absente)
   */
  reference?: string;

  /**
   * UUID du locataire (optionnel)
   */
  tenantId?: string;
}
