/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Réponse d'un paiement
 */
export interface PaymentResponse {
  agencyId?: string;
  amount?: number;
  amountPaid?: number;
  contractId?: string;
  createdAt?: string;
  dueDate?: string;
  id?: string;
  note?: string;
  overdue?: boolean;
  paidDate?: string;
  paymentMethod?: 'CASH' | 'BANK_TRANSFER' | 'MOBILE_MONEY' | 'CHECK';
  paymentType?: 'RENT' | 'DEPOSIT' | 'CHARGES' | 'COMMISSION' | 'SALE';
  periodLabel?: string;
  propertyId?: string;
  receiptUrl?: string;
  recordedById?: string;
  recordedByName?: string;
  reference?: string;
  status?: 'PENDING' | 'PAID' | 'LATE' | 'PARTIAL' | 'CANCELLED';
  tenantId?: string;
  updatedAt?: string;
}
