/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PresignedUrlResponse {
  bucket?: string;
  expiresInSeconds?: number;
  objectName?: string;
  publicUrl?: string;
  uploadUrl?: string;
}
