/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PresignedReadUrlResponse {
  bucket?: string;
  expiresInSeconds?: number;
  objectName?: string;
  readUrl?: string;
}
