/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PropertyMediaAddRequest {
  cover: boolean;
  fileName?: string;
  fileSize?: number;
  fileUrl?: string;
  mediaType?: string;
  mimeType?: string;
  sortOrder?: number;
}
