/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Paramètres du boost d'une annonce
 */
export interface PropertyBoostRequest {

  /**
   * Durée du boost en jours (1 à 365).
   */
  boostDays: number;
}
