/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PropertyDocumentResponse } from '../models/property-document-response';
import { PropertyMediaResponse } from '../models/property-media-response';
import { PropertyResponse } from '../models/property-response';
export interface PropertyDetailResponse {
  documents?: Array<PropertyDocumentResponse>;
  media?: Array<PropertyMediaResponse>;
  property?: PropertyResponse;
}
