/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PropertyMediaResponse {
  cover?: boolean;
  createdAt?: string;
  fileName?: string;
  fileSize?: number;
  fileUrl?: string;
  id?: string;
  mediaType?: string;
  mimeType?: string;
  propertyId?: string;
  sortOrder?: number;
  updatedAt?: string;
}
