/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PropertyUpdateRequest {
  acceptsPets?: boolean;
  address?: string;
  balconies?: number;
  bathrooms?: number;
  bedrooms?: number;
  city?: string;
  condition?: string;
  description?: string;
  district?: string;
  floor?: number;
  furnished?: boolean;
  hasAc?: boolean;
  hasElevator?: boolean;
  hasGarden?: boolean;
  hasGenerator?: boolean;
  hasParking?: boolean;
  hasPool?: boolean;
  hasSecurity?: boolean;
  hasWaterTank?: boolean;
  latitude?: number;
  longitude?: number;
  pmrAccessible?: boolean;
  price?: number;
  propertyType?: string;
  rooms?: number;
  street?: string;
  surfaceLiving?: number;
  surfaceTotal?: number;
  title?: string;
  totalFloors?: number;
  transactionType?: string;
  yearBuilt?: number;
}
