/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Date d'expiration automatique de l'annonce
 */
export interface PropertyExpirationRequest {

  /**
   * Date et heure d'expiration de l'annonce. Doit être dans le futur.
   */
  expiresAt: string;
}
