/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RegisterCompleteRequest {
  email?: string;
  firstName?: string;
  lastName?: string;
  password?: string;
  phone?: string;
  title?: string;
}
