/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Détail d'une réservation
 */
export interface ReservationResponse {
  cancellationReason?: string;
  cancelledAt?: string;
  cancelledById?: string;
  checkInDate?: string;
  checkOutDate?: string;
  clientEmail?: string;
  clientFullName?: string;
  clientId?: string;
  completedAt?: string;
  confirmedAt?: string;
  createdAt?: string;
  guestCount?: number;
  id?: string;
  notes?: string;
  numberOfNights?: number;
  pricePerNight?: number;
  propertyCity?: string;
  propertyId?: string;
  propertyTitle?: string;
  status?: 'PENDING' | 'CONFIRMED' | 'CANCELLED' | 'COMPLETED' | 'NO_SHOW';
  totalAmount?: number;
  updatedAt?: string;
}
