/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TenantCreateRequest {
  employerName?: string;
  employmentStatus?: string;
  guarantorEmail?: string;
  guarantorName?: string;
  guarantorPhone?: string;
  hasGuarantor?: boolean;
  monthlyIncome?: number;
}
