/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TenantResponse {
  addressProofUrl?: string;
  createdAt?: string;
  email?: string;
  employerName?: string;
  employmentStatus?: string;
  fullName?: string;
  guarantorEmail?: string;
  guarantorName?: string;
  guarantorPhone?: string;
  hasGuarantor?: boolean;
  id?: string;
  idDocumentExpiry?: string;
  idDocumentNumber?: string;
  idDocumentType?: string;
  idDocumentUrl?: string;
  incomeProofUrl?: string;
  monthlyIncome?: number;
  qualified?: boolean;
  qualifiedAt?: string;
  rejectionReason?: string;
  status?: 'INCOMPLETE' | 'PENDING_REVIEW' | 'QUALIFIED' | 'REJECTED' | 'BLACKLISTED';
  updatedAt?: string;
  userId?: string;
}
