/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UserSubRoleResponse } from '../models/user-sub-role-response';
export interface UserResponse {
  active?: boolean;
  address?: string;
  agencyId?: string;
  agencyName?: string;
  avatarUrl?: string;
  city?: string;
  country?: string;
  createdAt?: string;
  dateOfBirth?: string;
  email?: string;
  emailVerified?: boolean;
  firstName?: string;
  hotelId?: string;
  hotelName?: string;
  identityVerified?: boolean;
  keycloakId?: string;
  language?: string;
  lastLoginAt?: string;
  lastName?: string;
  partnerType?: string;
  phone?: string;
  phoneVerified?: boolean;
  roles?: Array<'CLIENT' | 'OWNER' | 'ADMIN' | 'SUPER_ADMIN' | 'PARTNER' | 'PARTNER_ADMIN'>;
  subRoles?: Array<UserSubRoleResponse>;
  updatedAt?: string;
  userId?: string;
}
