/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { VisitRequestResponse } from '../../models/visit-request-response';

export interface GetDetail$Params {

/**
 * ID de la demande de visite
 */
  visitRequestId: string;
}

export function getDetail(http: HttpClient, rootUrl: string, params: GetDetail$Params, context?: HttpContext): Observable<StrictHttpResponse<VisitRequestResponse>> {
  const rb = new RequestBuilder(rootUrl, getDetail.PATH, 'get');
  if (params) {
    rb.path('visitRequestId', params.visitRequestId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<VisitRequestResponse>;
    })
  );
}

getDetail.PATH = '/v1/property-visits/{visitRequestId}';
