/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { VisitAvailabilityResponse } from '../../models/visit-availability-response';

export interface GetAvailableSlots$Params {

/**
 * ID du bien immobilier
 */
  propertyId: string;

/**
 * Nombre de jours à scanner à partir d'aujourd'hui (défaut : 30)
 */
  daysAhead?: number;
}

export function getAvailableSlots(http: HttpClient, rootUrl: string, params: GetAvailableSlots$Params, context?: HttpContext): Observable<StrictHttpResponse<VisitAvailabilityResponse>> {
  const rb = new RequestBuilder(rootUrl, getAvailableSlots.PATH, 'get');
  if (params) {
    rb.path('propertyId', params.propertyId, {});
    rb.query('daysAhead', params.daysAhead, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<VisitAvailabilityResponse>;
    })
  );
}

getAvailableSlots.PATH = '/v1/property-visits/available-slots/{propertyId}';
