/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PartnerApplicationResponse } from '../../models/partner-application-response';

export interface Decide$Params {
  id: string;

/**
 * Nouveau statut. PENDING est interdit (réservé à la soumission).
 */
  newStatus: 'UNDER_REVIEW' | 'APPROVED' | 'REJECTED' | 'INCOMPLETE';

/**
 * Motif obligatoire si newStatus est REJECTED ou INCOMPLETE
 */
  comment?: string;
}

export function decide(http: HttpClient, rootUrl: string, params: Decide$Params, context?: HttpContext): Observable<StrictHttpResponse<PartnerApplicationResponse>> {
  const rb = new RequestBuilder(rootUrl, decide.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.query('newStatus', params.newStatus, {});
    rb.query('comment', params.comment, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PartnerApplicationResponse>;
    })
  );
}

decide.PATH = '/v1/partner/admin/applications/{id}/decision';
