/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Pageable } from '../../models/pageable';
import { PartnerApplicationResponse } from '../../models/partner-application-response';

export interface ListApplications$Params {
  status?: 'PENDING' | 'UNDER_REVIEW' | 'INCOMPLETE' | 'APPROVED' | 'REJECTED';
  pageable: Pageable;
}

export function listApplications(http: HttpClient, rootUrl: string, params: ListApplications$Params, context?: HttpContext): Observable<StrictHttpResponse<PartnerApplicationResponse>> {
  const rb = new RequestBuilder(rootUrl, listApplications.PATH, 'get');
  if (params) {
    rb.query('status', params.status, {});
    rb.query('pageable', params.pageable, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PartnerApplicationResponse>;
    })
  );
}

listApplications.PATH = '/v1/partner/admin/applications';
