/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ExpenseResponse } from '../../models/expense-response';
import { Pageable } from '../../models/pageable';

export interface List3$Params {
  category?: 'MAINTENANCE' | 'MARKETING' | 'SALARY' | 'UTILITIES' | 'TAX' | 'OTHER';
  propertyId?: string;
  from?: string;
  to?: string;
  pageable: Pageable;
}

export function list3(http: HttpClient, rootUrl: string, params: List3$Params, context?: HttpContext): Observable<StrictHttpResponse<ExpenseResponse>> {
  const rb = new RequestBuilder(rootUrl, list3.PATH, 'get');
  if (params) {
    rb.query('category', params.category, {});
    rb.query('propertyId', params.propertyId, {});
    rb.query('from', params.from, {});
    rb.query('to', params.to, {});
    rb.query('pageable', params.pageable, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ExpenseResponse>;
    })
  );
}

list3.PATH = '/v1/expenses';
