/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { LaCodeListDto } from '../../models/la-code-list-dto';

export interface Create7$Params {
      body: LaCodeListDto
}

export function create7(http: HttpClient, rootUrl: string, params: Create7$Params, context?: HttpContext): Observable<StrictHttpResponse<LaCodeListDto>> {
  const rb = new RequestBuilder(rootUrl, create7.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<LaCodeListDto>;
    })
  );
}

create7.PATH = '/v1/code-list';
