/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { LaCodeListDto } from '../../models/la-code-list-dto';

export interface FindAllByTypeAdmin$Params {
  type: string;
}

export function findAllByTypeAdmin(http: HttpClient, rootUrl: string, params: FindAllByTypeAdmin$Params, context?: HttpContext): Observable<StrictHttpResponse<LaCodeListDto>> {
  const rb = new RequestBuilder(rootUrl, findAllByTypeAdmin.PATH, 'get');
  if (params) {
    rb.path('type', params.type, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<LaCodeListDto>;
    })
  );
}

findAllByTypeAdmin.PATH = '/v1/code-list/admin/type/{type}';
