import type {
  DashboardDonutLegendItem,
  DashboardKpiCard,
  DashboardPropertyRow,
  DashboardRevenueBar,
  DashboardTransaction,
} from '../types/dashboard-dg.types';

export const PAGE_SIZE = 8;
export const REVENUE_MAX = 10_000_000;

export const DASHBOARD_ICONS = {
  search: 'archivages/commercial/icons/search.webp',
  calendar: 'archivages/commercial/icons/calendar-toolbar.webp',
  export: 'archivages/commercial/icons/export.webp',
  chevronDown: 'archivages/commercial/icons/chevron-down.webp',
  eye: 'client-detail/icons/eye.svg',
  paginatorPrevious: 'archivages/commercial/icons/paginator-previous.webp',
  paginatorNext: 'archivages/commercial/icons/paginator-next.webp',
} as const;

export const KPI_CARDS: readonly DashboardKpiCard[] = [
  {
    label: 'Tous les biens',
    value: '45',
    trend: '+2%',
    tone: 'all',
    iconSrc: 'rooms/icons/stat-all.svg',
  },
  {
    label: 'Annonces actives',
    value: '10',
    tone: 'active',
    iconSrc: 'rooms/icons/stat-online.svg',
  },
  {
    label: 'Biens Loués',
    value: '33',
    tone: 'rented',
    iconSrc: 'rooms/icons/stat-occupied.svg',
  },
  {
    label: 'Biens Vendus',
    value: '2',
    tone: 'sold',
    iconSrc: 'rooms/icons/stat-reserved.svg',
  },
];

export const DONUT_LEGEND: readonly DashboardDonutLegendItem[] = [
  { count: 9, label: 'Occupés', tone: 'occupied' },
  { count: 6, label: 'Disponibles', tone: 'available' },
  { count: 12, label: 'Réservés', tone: 'reserved' },
  { count: 2, label: 'En maintenance', tone: 'maintenance' },
];

export const REVENUE_BARS: readonly DashboardRevenueBar[] = [
  { label: 'JAN', slug: 'jan', value: 1_000_000 },
  { label: 'FEV', slug: 'fev', value: 3_150_000 },
  { label: 'MAR', slug: 'mar', value: 4_450_000 },
  { label: 'AVR', slug: 'avr', value: 1_000_000 },
  { label: 'MAI', slug: 'mai', value: 2_950_000 },
  { label: 'JUI', slug: 'jui-1', value: 6_730_000, highlighted: true },
  { label: 'JUI', slug: 'jui-2', value: 2_250_000 },
  { label: 'AOU', slug: 'aou', value: 1_280_000 },
  { label: 'SEP', slug: 'sep', value: 3_150_000 },
  { label: 'OCT', slug: 'oct', value: 1_000_000 },
  { label: 'NOV', slug: 'nov', value: 3_150_000 },
  { label: 'DEC', slug: 'dec', value: 4_450_000 },
];

export const OVERVIEW_PROPERTIES: readonly DashboardPropertyRow[] = [
  {
    uid: 'overview-1',
    id: 'UBX-001',
    name: 'Immeuble kalia',
    type: 'Appartement',
    location: 'Abidjan, Cocody',
    price: '450 000 FCFA/mois',
    tenant: 'Koné Ibrahim',
    status: 'Actif',
    avatar: 'biens/list/list-tenant-01.webp',
  },
  {
    uid: 'overview-2',
    id: 'UBX-002',
    name: 'Villa Riviera',
    type: 'Villa',
    location: 'Abidjan, Riviera',
    price: '600 000 FCFA/mois',
    tenant: 'Koffi Didier',
    status: 'Actif',
    avatar: 'shared/people/profile-01.webp',
  },
  {
    uid: 'overview-3',
    id: 'UBX-003',
    name: 'Villa Riviera',
    type: 'Villa',
    location: 'Abidjan, Riviera',
    price: '600 000 FCFA/mois',
    tenant: 'Kouamé Patrick',
    status: 'Actif',
    avatar: 'shared/people/profile-02.webp',
  },
  {
    uid: 'overview-4',
    id: 'UBX-004',
    name: 'résidence Plateau',
    type: 'Appartement',
    location: 'Abidjan, Plateau',
    price: '250 000 FCFA/mois',
    tenant: 'Konan Olivier',
    status: 'Actif',
    avatar: 'shared/people/profile-03.webp',
  },
  {
    uid: 'overview-5',
    id: 'UBX-005',
    name: 'Villa Riviera',
    type: 'Villa',
    location: 'Abidjan, Riviera',
    price: '600 000 FCFA/mois',
    tenant: 'Konan Olivier',
    status: 'Actif',
    avatar: 'shared/people/receipt-guest-01.webp',
  },
  {
    uid: 'overview-6',
    id: 'UBX-001',
    name: 'Immeuble kalia',
    type: 'Appartement',
    location: 'Abidjan, Cocody',
    price: '450 000 FCFA/mois',
    tenant: 'Konan Olivier',
    status: 'Actif',
    avatar: 'shared/people/receipt-guest-02.webp',
  },
  {
    uid: 'overview-7',
    id: 'UBX-002',
    name: 'Villa Riviera',
    type: 'Villa',
    location: 'Abidjan, Riviera',
    price: '600 000 FCFA/mois',
    tenant: 'Koffi Didier',
    status: 'Actif',
    avatar: 'shared/people/receipt-guest-03.webp',
  },
  {
    uid: 'overview-8',
    id: 'UBX-003',
    name: 'Villa Riviera',
    type: 'Villa',
    location: 'Abidjan, Riviera',
    price: '600 000 FCFA/mois',
    tenant: 'Kouamé Patrick',
    status: 'Actif',
    avatar: 'shared/people/receipt-guest-04.webp',
  },
  {
    uid: 'overview-9',
    id: 'UBX-004',
    name: 'résidence Plateau',
    type: 'Appartement',
    location: 'Abidjan, Plateau',
    price: '250 000 FCFA/mois',
    tenant: 'Konan Olivier',
    status: 'Actif',
    avatar: 'shared/people/receipt-guest-05.webp',
  },
  {
    uid: 'overview-10',
    id: 'UBX-005',
    name: 'Villa Riviera',
    type: 'Villa',
    location: 'Abidjan, Riviera',
    price: '600 000 FCFA/mois',
    tenant: 'Konan Olivier',
    status: 'Actif',
    avatar: 'biens/bailleur/tenant-02.webp',
  },
];

export const FULL_LIST_PROPERTIES: readonly DashboardPropertyRow[] = Array.from(
  { length: PAGE_SIZE * 5 },
  (_, index) => ({
    uid: `full-${index + 1}`,
    id: 'UBX-001',
    name: 'Immeuble kalia',
    type: 'Appartement',
    location: 'Abidjan, Cocody',
    price: '450 000 FCFA/mois',
    tenant: 'Koné Ibrahim',
    status: 'Actif',
    avatar: 'biens/list/list-tenant-01.webp',
  }),
);

export const TRANSACTIONS: readonly DashboardTransaction[] = [
  {
    uid: 'txn-1',
    title: 'Réception paiement Location',
    date: '5 Avril 2026 à 12 : 30',
    customer: 'Koné Ibrahim',
    amount: '+ 450 000 FCFA',
    month: 'Mars 2026',
    logo: 'biens/bailleur/payment-wave.webp',
  },
  {
    uid: 'txn-2',
    title: 'Réception paiement Location',
    date: '2 Avril 2026 à 17 : 41',
    customer: 'Koffi Didier',
    amount: '+ 600 000 FCFA',
    month: 'Mars 2026',
    logo: 'biens/bailleur/payment-orange.webp',
  },
  {
    uid: 'txn-3',
    title: 'Réception paiement Location',
    date: '2 Avril 2026 à 17 : 41',
    customer: 'Konan Olivier',
    amount: '+ 250 000 FCFA',
    month: 'Mars 2026',
    logo: 'biens/bailleur/payment-orange.webp',
  },
  {
    uid: 'txn-4',
    title: 'Réception paiement Location',
    date: '2 Avril 2026 à 17 : 41',
    customer: 'Koffi Didier',
    amount: '+ 600 000 FCFA',
    month: 'Mars 2026',
    logo: 'biens/bailleur/payment-wave.webp',
  },
  {
    uid: 'txn-5',
    title: 'Réception paiement Location',
    date: '5 Avril 2026 à 12 : 30',
    customer: 'Koné Ibrahim',
    amount: '+ 450 000 FCFA',
    month: 'Mars 2026',
    logo: 'biens/bailleur/payment-wave.webp',
  },
  {
    uid: 'txn-6',
    title: 'Réception paiement Location',
    date: '5 Avril 2026 à 12 : 30',
    customer: 'Koné Ibrahim',
    amount: '+ 450 000 FCFA',
    month: 'Mars 2026',
    logo: 'biens/bailleur/payment-wave.webp',
  },
  {
    uid: 'txn-7',
    title: 'Réception paiement Location',
    date: '2 Avril 2026 à 17 : 41',
    customer: 'Koffi Didier',
    amount: '+ 600 000 FCFA',
    month: 'Mars 2026',
    logo: 'biens/bailleur/payment-orange.webp',
  },
  {
    uid: 'txn-8',
    title: 'Réception paiement Location',
    date: '2 Avril 2026 à 17 : 41',
    customer: 'Konan Olivier',
    amount: '+ 250 000 FCFA',
    month: 'Mars 2026',
    logo: 'biens/bailleur/payment-orange.webp',
  },
  {
    uid: 'txn-9',
    title: 'Réception paiement Location',
    date: '2 Avril 2026 à 17 : 41',
    customer: 'Koffi Didier',
    amount: '+ 600 000 FCFA',
    month: 'Mars 2026',
    logo: 'biens/bailleur/payment-wave.webp',
  },
  {
    uid: 'txn-10',
    title: 'Réception paiement Location',
    date: '5 Avril 2026 à 12 : 30',
    customer: 'Koné Ibrahim',
    amount: '+ 450 000 FCFA',
    month: 'Mars 2026',
    logo: 'biens/bailleur/payment-wave.webp',
  },
];
